# Generated by Django 6.0.5 on 2026-05-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitoGeorreferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTACION', 'Estación'), ('PUENTE', 'Puente'), ('TUNEL', 'Túnel'), ('CRUCE', 'Cruce'), ('SEÑAL', 'Señal'), ('OTRO', 'Otro')], default='ESTACION', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('punto_kilometrico', models.FloatField(blank=True, db_column='pk', null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_por', models.CharField(blank=True, max_length=100)),
                ('ts_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hitos_georreferencia',
            },
        ),
    ]
