# Generated by Django 6.0.5 on 2026-05-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tren_num', models.CharField(blank=True, max_length=20)),
                ('equipo_id', models.CharField(blank=True, max_length=20)),
                ('estacion', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('minutos', models.IntegerField(default=0)),
                ('categoria', models.CharField(blank=True, choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('GRAVE', 'Grave')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('hora_programada', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'novedades_operativas',
            },
        ),
        migrations.CreateModel(
            name='ReporteFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cargo', models.CharField(blank=True, max_length=50)),
                ('resumen_texto', models.TextField(blank=True)),
                ('reporte_texto', models.TextField(blank=True)),
                ('justificacion_cierre', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes_finales',
            },
        ),
    ]
