# Generated by Django 6.0.5 on 2026-05-30 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitacora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefinal',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_finales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedadoperativa',
            name='reporte',
            field=models.ForeignKey(db_column='reporte_id', on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='bitacora.reportefinal'),
        ),
    ]
