# Generated by Django 6.0.5 on 2026-05-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('tramo_desde', models.CharField(blank=True, max_length=100)),
                ('tramo_hasta', models.CharField(blank=True, max_length=100)),
                ('via', models.CharField(blank=True, max_length=20)),
                ('pk_inicio', models.FloatField(blank=True, null=True)),
                ('pk_termino', models.FloatField(blank=True, null=True)),
                ('texto_original_km', models.TextField(blank=True)),
                ('velocidad_restriccion', models.CharField(blank=True, max_length=20)),
                ('causa', models.TextField(blank=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=10)),
                ('hora_termino', models.CharField(blank=True, max_length=10)),
                ('encargado', models.CharField(blank=True, max_length=100)),
                ('seccion', models.CharField(choices=[('faena_inicio', 'Notificación de faenas en inicio'), ('cortada', 'Programación de cortadas')], default='faena_inicio', max_length=30)),
            ],
            options={
                'db_table': 'prevenciones_activas',
            },
        ),
        migrations.CreateModel(
            name='EstacionVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=20)),
                ('via', models.CharField(max_length=10)),
                ('posicion', models.CharField(blank=True, max_length=10)),
                ('etiqueta', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'estaciones_vias',
                'unique_together': {('estacion', 'via', 'posicion')},
            },
        ),
    ]
