# Generated by Django 6.0.5 on 2026-06-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevenciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prevencion',
            name='bloque_afectado',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prevencion',
            name='descripcion_trabajo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prevencion',
            name='km_fin',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='prevencion',
            name='km_inicio',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='prevencion',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prevencion',
            name='linea',
            field=models.CharField(blank=True, choices=[('L1', 'Línea 1'), ('L2', 'Línea 2')], max_length=5),
        ),
        migrations.AddField(
            model_name='prevencion',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prevencion',
            name='tipo_restriccion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='prevencion',
            name='velocidad_restriccion',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='prevencion',
            name='via',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
