# Generated by Django 6.0.5 on 2026-05-30 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('GERENCIA', 'Gerencia'), ('IL', 'Inspector de Línea'), ('INSPECTOR DE LINEA', 'Inspector de Línea'), ('SL', 'Supervisor de Línea'), ('SUPERVISOR DE LINEA', 'Supervisor de Línea'), ('JEFE DE OPERACIONES', 'Jefe de Operaciones'), ('JEFE SERVICIO', 'Jefe de Servicio'), ('JEFE DE SERVICIO', 'Jefe de Servicio'), ('MAQUINISTA', 'Maquinista'), ('AYUDANTE', 'Ayudante')], default='MAQUINISTA', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lugar_apertura', models.CharField(blank=True, max_length=100)),
                ('hora_apertura', models.CharField(blank=True, max_length=10)),
                ('inicio_servicio', models.CharField(blank=True, max_length=10)),
                ('hora_cierre', models.CharField(blank=True, max_length=10)),
                ('horas_extras', models.FloatField(default=0)),
                ('horas_menos_reposo', models.FloatField(default=0)),
                ('horas_nocturnas', models.FloatField(default=0)),
                ('horas_manejo', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('observacion_il', models.TextField(blank=True)),
                ('rut_trabajador', models.ForeignKey(db_column='rut_trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='registros_operativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_operativo',
            },
        ),
        migrations.CreateModel(
            name='AusenciaTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('LICENCIA', 'Licencia'), ('PERMISO', 'Permiso'), ('BAJA', 'Baja'), ('VACACIONES', 'Vacaciones')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('dias', models.IntegerField(default=1)),
                ('registrado_por', models.CharField(blank=True, max_length=100)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ausencias_temporales',
                'unique_together': {('fecha', 'rut')},
            },
        ),
    ]
