# Generated by Django 6.0.5 on 2026-06-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrooperativo',
            name='grafico_apertura_hora',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registrooperativo',
            name='grafico_cierre_hora',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registrooperativo',
            name='grafico_tiene_descanso_posterior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrooperativo',
            name='horas_extras_7_5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrooperativo',
            name='horas_extras_apertura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrooperativo',
            name='horas_extras_cierre',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrooperativo',
            name='horas_extras_descanso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrooperativo',
            name='horas_extras_doble_turno',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='registrooperativo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_AUTORIZACION', 'Pendiente Autorización IL'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=30),
        ),
    ]
