# Generated by Django 6.0.5 on 2026-05-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraficoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('num_turno', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'grafico_mensual',
            },
        ),
        migrations.CreateModel(
            name='ItinerarioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('equipo', models.CharField(max_length=20)),
                ('inicio', models.CharField(blank=True, max_length=100)),
                ('servicios_am', models.TextField(blank=True)),
                ('destino_medio', models.CharField(blank=True, max_length=100)),
                ('servicios_pm', models.TextField(blank=True)),
                ('destino_final', models.CharField(blank=True, max_length=100)),
                ('destino_final_real', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('MODIFICADO', 'Modificado'), ('CERRADO', 'Cerrado')], default='PLANIFICADO', max_length=20)),
                ('modificado_por', models.CharField(blank=True, max_length=100)),
                ('ts_modificacion', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'itinerario_equipos',
            },
        ),
        migrations.CreateModel(
            name='MaestroTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_turno', models.CharField(max_length=10)),
                ('tipo_dia', models.CharField(max_length=20)),
                ('apertura_lugar', models.CharField(blank=True, max_length=100)),
                ('apertura_hora', models.CharField(blank=True, max_length=10)),
                ('presentacion_lugar', models.CharField(blank=True, max_length=100)),
                ('presentacion_hora', models.CharField(blank=True, max_length=10)),
                ('servicios', models.TextField(blank=True)),
                ('cierre_lugar', models.CharField(blank=True, max_length=100)),
                ('cierre_hora', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'maestro_turnos',
            },
        ),
        migrations.CreateModel(
            name='RegistroEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tren_num', models.CharField(max_length=20)),
                ('estacion_id', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A LA HORA', 'A la hora'), ('ATRASO', 'Atraso'), ('SIN MARCAR', 'Sin marcar')], default='SIN MARCAR', max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registros_estaciones',
            },
        ),
        migrations.CreateModel(
            name='ServicioActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tren_num', models.CharField(max_length=20)),
                ('equipo_id', models.CharField(blank=True, max_length=20)),
                ('maquinista', models.CharField(blank=True, max_length=100)),
                ('ayudante', models.CharField(blank=True, max_length=100)),
                ('rut_maquinista', models.CharField(blank=True, max_length=20)),
                ('rut_ayudante', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado'), ('EMERGENCIA', 'Emergencia')], default='ACTIVO', max_length=20)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('timestamp_gps', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios_activos',
            },
        ),
        migrations.CreateModel(
            name='ServicioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tren_num', models.CharField(max_length=20)),
                ('equipo_id', models.CharField(blank=True, max_length=20)),
                ('maquinista', models.CharField(blank=True, max_length=100)),
                ('ayudante', models.CharField(blank=True, max_length=100)),
                ('rut_maquinista', models.CharField(blank=True, max_length=20)),
                ('rut_ayudante', models.CharField(blank=True, max_length=20)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='CERRADO', max_length=20)),
            ],
            options={
                'db_table': 'servicios_historicos',
            },
        ),
    ]
