# Generated by Django 6.0.5 on 2026-05-30 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graficomensual',
            name='rut',
            field=models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, related_name='grafico_mensual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='itinerarioequipo',
            unique_together={('fecha', 'equipo')},
        ),
        migrations.AlterUniqueTogether(
            name='maestroturno',
            unique_together={('num_turno', 'tipo_dia')},
        ),
        migrations.AlterUniqueTogether(
            name='registroestacion',
            unique_together={('fecha', 'tren_num', 'estacion_id')},
        ),
        migrations.AlterUniqueTogether(
            name='servicioactivo',
            unique_together={('fecha', 'tren_num')},
        ),
        migrations.AlterUniqueTogether(
            name='serviciohistorico',
            unique_together={('fecha', 'tren_num')},
        ),
        migrations.AlterUniqueTogether(
            name='graficomensual',
            unique_together={('fecha', 'rut')},
        ),
    ]
