# Generated by Django 6.0.5 on 2026-06-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItinerarioMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tren_num', models.CharField(max_length=20)),
                ('tipo_dia', models.CharField(max_length=10)),
                ('ruta_id', models.CharField(max_length=50)),
                ('estacion_nombre', models.CharField(max_length=100)),
                ('orden_estacion', models.IntegerField()),
                ('hora_programada', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itinerario_maestro',
                'unique_together': {('tren_num', 'tipo_dia', 'estacion_nombre')},
            },
        ),
        migrations.CreateModel(
            name='RutaEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_id', models.CharField(max_length=50)),
                ('estacion_nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'rutas_estaciones',
                'unique_together': {('ruta_id', 'orden')},
            },
        ),
    ]
