# Generated by Django 6.0.5 on 2026-06-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_itinerariomaestro_rutaestacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='ParejaTripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('ayudante', models.ForeignKey(blank=True, db_column='ayudante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parejas_ayudante', to=settings.AUTH_USER_MODEL)),
                ('maquinista', models.ForeignKey(blank=True, db_column='maquinista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parejas_maquinista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parejas_tripulacion',
                'ordering': ['orden'],
            },
        ),
    ]
