# Generated by Django 6.0.5 on 2026-05-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tren_num', models.CharField(blank=True, max_length=20)),
                ('equipo', models.CharField(blank=True, max_length=20)),
                ('maquinista', models.CharField(blank=True, max_length=100)),
                ('ayudante', models.CharField(blank=True, max_length=100)),
                ('estado_tripulacion', models.CharField(blank=True, max_length=50)),
                ('tipo_evento', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.TextField(blank=True)),
                ('estado_alerta', models.CharField(choices=[('ACTIVA', 'Activa'), ('CONTROLADA', 'Controlada'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emergencias_activas',
            },
        ),
        migrations.CreateModel(
            name='FallaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tren_num', models.CharField(blank=True, max_length=20)),
                ('equipo', models.CharField(blank=True, max_length=20)),
                ('rut_reporta', models.CharField(blank=True, max_length=20)),
                ('nombre_reporta', models.CharField(blank=True, max_length=100)),
                ('sistema_afectado', models.CharField(blank=True, max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GESTIONADA', 'Gestionada'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'db_table': 'fallas_equipos',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('tren_num', models.CharField(blank=True, max_length=20)),
                ('equipo', models.CharField(blank=True, max_length=20)),
                ('maquinista', models.CharField(blank=True, max_length=100)),
                ('ayudante', models.CharField(blank=True, max_length=100)),
                ('rut_reporta', models.CharField(blank=True, max_length=20)),
                ('nombre_reporta', models.CharField(blank=True, max_length=100)),
                ('tipo_incidencia', models.CharField(choices=[('Infraestructura y Vía (Vía y Obras)', 'Infraestructura y Vía (Vía y Obras)'), ('Sistemas de Señalización y Comunicaciones', 'Sistemas de Señalización y Comunicaciones'), ('Operación y Tráfico', 'Operación y Tráfico'), ('Emergencia Médica o Comercial', 'Emergencia Médica o Comercial')], max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('ubicacion', models.TextField(blank=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN GESTION', 'En gestión'), ('RESUELTA', 'Resuelta')], default='REGISTRADA', max_length=20)),
            ],
            options={
                'db_table': 'incidencias_ferroviarias',
            },
        ),
    ]
