# Generated by Django 6.0.5 on 2026-06-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallaequipo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fallaequipo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
