# Generated by Django 6.0.5 on 2026-06-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_fallaequipo_latitud_fallaequipo_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='nombre_reporta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='rut_reporta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo_incidencia',
            field=models.CharField(max_length=100),
        ),
    ]
