services:
  - type: web
    name: syncro-red-backend
    runtime: python
    rootDir: Syncro_Red_Backend
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT efe_sur.asgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_SSLMODE
        value: "require"
      - key: REDIS_URL
        sync: false
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHON_VERSION
        value: "3.12.0"
